# Basic Python

## 1. Split this string

In [24]:
s = "Hi there Sam!"

In [25]:
txt = "Hi there Sam!"
x = txt.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [26]:
planet = "Earth"
diameter = 12742

In [27]:
planet ="Earth"
diameter="12742"
print('The diameter of {} is {} kilometer.'.format(planet,diameter));

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [28]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [29]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print (d['k1'][3]["tricky"][3]['target'][3])


hello


# Numpy

In [30]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [31]:
import numpy as np
array = np.zeros(10)
print("Array of 10 zeros:")
print(array)

Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
import numpy as np
array = np.ones(10)*5
print("Array of 10 fives:")
print(array)

Array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [33]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [34]:
import numpy as np
x = np.arange(0 , 9).reshape(3,3)
print (x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [35]:
import numpy as np
array1 = np.array([[1,2,3]])
array2= np.array([[4,5,6]])
x= np.concatenate((array1 , array2),axis = None)
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [36]:
import pandas as pd


In [37]:
import pandas as pd
lst = [[1,'Amish',20],[2, 'Priyanka' , 20],[3,'Swathi' ,20]]
df = pd.DataFrame(lst,columns =['S.N0' , 'name', 'age'])
print(df)

   S.N0      name  age
0     1     Amish   20
1     2  Priyanka   20
2     3    Swathi   20


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [38]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [39]:
import pandas as pd
lst = [[1,'aaa',22],[2, 'bbb' , 24]]
df = pd.DataFrame(lst,columns =['S.N0' , 'name', 'age'])
print(df)

   S.N0 name  age
0     1  aaa   22
1     2  bbb   24
