# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
txt="hi there sam!"
x=txt.split()
print(x)


['hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet="Earth"
diameter="12742"
print('The diameter of {} is {} kilometer.'.format(planet,diameter));

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
array=np.zeros(10)
print("array of 10 zeros:")
print(array)

array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
array=np.ones(10)*4
print("array of 10 fours:")
print(array)

array of 10 fours:
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array=np.arange(20,35,2)
print("array of all the even integers from 20 to 35")
print(array)


array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(array)

[20 22 24 26 28 30 32 34]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [20]:
import pandas as pd
lst = [[1,'Mithy',2],[2, 'dhiya' ,8],[3, 'dhiva' ,3]]
df = pd.DataFrame(lst,columns =['S.No','name','age'])
print(df) 

   S.No   name  age
0     1  Mithy    2
1     2  dhiya    8
2     3  dhiva    3


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
import datetime
import pandas as pd

test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")


K=41

date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%y"))


Index(['01-01-23', '02-01-23', '03-01-23', '04-01-23', '05-01-23', '06-01-23',
       '07-01-23', '08-01-23', '09-01-23', '10-01-23', '11-01-23', '12-01-23',
       '13-01-23', '14-01-23', '15-01-23', '16-01-23', '17-01-23', '18-01-23',
       '19-01-23', '20-01-23', '21-01-23', '22-01-23', '23-01-23', '24-01-23',
       '25-01-23', '26-01-23', '27-01-23', '28-01-23', '29-01-23', '30-01-23',
       '31-01-23', '01-02-23', '02-02-23', '03-02-23', '04-02-23', '05-02-23',
       '06-02-23', '07-02-23', '08-02-23', '09-02-23', '10-02-23'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
import pandas as pd
lst = [[1,'aaa',22],[2, 'bbb' ,24]]
df = pd.DataFrame(lst,columns =['S.NO','name','age'])
print(df)

   S.NO name  age
0     1  aaa   22
1     2  bbb   24
